config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'authentication/index' 
  
  resources :stats
  post 'search' => 'stats#search'

  resources :activities
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'authentication#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def index
	# Turn off SSL for now
	ctx = OpenSSL::SSL::SSLContext.new
	ctx.verify_mode = OpenSSL::SSL::VERIFY_NONE
	
	# GET Request to strava to get ALL stats for the hardcoded athlete id
	body = HTTP.get("https://www.strava.com/api/v3/athlete/activities", :ssl_context => ctx, :params => {:access_token => "397ecd551200ef80d5b67bb3ccdd4cb8edccd01a"})
	
	print "body: " + body
	
	# parse the JSON response and put it into an Hash instance variable 
	@activities = JSON.parse(body)
	
	print "activities: " + @activities[0]["id"].to_s
	
	# render the default view for this controller and action, i.e., stats#index
	render
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authentication_controller.rb
require 'http'

class AuthenticationController < ApplicationController
  def index
  end
  
  def doOauth
	# GET Request to Strava for user to grant permissions
	redirect_to "https://www.strava.com/oauth/authorize?client_id=23094&redirect_uri=http://localhost:3000/authentication/doTokenExchange&response_type=code&approval_prompt=force"
  end
  
  # Action is executed by Strava via the redirect_uri above once the user has granted permissions for this approval_prompt
  # to access Strava
  def doTokenExchange
	# Turn off SSL for now
	ctx = OpenSSL::SSL::SSLContext.new
	ctx.verify_mode = OpenSSL::SSL::VERIFY_NONE
	
	# GET Request to Strava to exchange client info for an access token
	body = HTTP.post("https://www.strava.com/oauth/token", :ssl_context => ctx, :params => {:client_id => "23094", :client_secret => "19ed34edde4dc72c9bac1a672e107c67d0d20f7e", :code => params[:code]})
	
	# parse the JSON response to get the access token (used for future requests) and profile information for the user
	@response = JSON.parse(body)
	
	session[:access_token] = @response['access_token']	
	session[:user_profile] = @response['athlete']

	
	puts "access_token: " + session[:access_token]
	puts "user_profile: " + session[:user_profile]['profile']
	
	redirect_to welcome_index_path
  end
end

app/controllers/stats_controller.rb
require 'json'

class StatsController < ApplicationController
  def index
	# Turn off SSL for now
	ctx = OpenSSL::SSL::SSLContext.new
	ctx.verify_mode = OpenSSL::SSL::VERIFY_NONE
	
	# GET Request to strava to get ALL stats for the hardcoded athlete id
	body = HTTP.get("https://www.strava.com/api/v3/athletes/2665988/stats", :ssl_context => ctx, :params => {:access_token => "397ecd551200ef80d5b67bb3ccdd4cb8edccd01a"})
	
	print "body: " + body
	
	# parse the JSON response and put it into an Hash instance variable 
	@stats = JSON.parse(body)
	
	# render the default view for this controller and action, i.e., stats#index
	render
  end
  
  def search
	# Turn off SSL for now
	ctx = OpenSSL::SSL::SSLContext.new
	ctx.verify_mode = OpenSSL::SSL::VERIFY_NONE
	
	# GET Request to strava to get ALL stats for the hardcoded athlete id
	body = HTTP.get("https://www.strava.com/api/v3/athletes/2665988/stats", :ssl_context => ctx, :params => {:access_token => "397ecd551200ef80d5b67bb3ccdd4cb8edccd01a"})
	
	# parse the JSON response and put it into an Hash instance variable 
	@stats = JSON.parse(body)
	
	# pull out the specific stat in question which was passed as a request param
	@stat = @stats[params[:stat_name]];
	
	# render the default view for this controller and action, i.e., stats#show
	render
  end
end

app/controllers/welcome_controller.rb
require 'http'

class WelcomeController < ApplicationController
  def index
	@profile = session[:user_profile]
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/activities/index.html.erb
<h1>All Activities</h1>
 
<table>
  <tr>
    <th>Date</th>
    <th>ID</th>
    <th>Name</th>
    <th>Distance</th>
  </tr>
 
  <% @activities.each do |value| %>
    <tr>
      <td><%= value["start_date"] %></td>
      <td><%= value["id"] %></td>
      <td><%= value["name"] %></td>
      <td><%= value["distance"] %></td>
    </tr>
  <% end %>
</table>

<br/>

<%= link_to 'Home', welcome_index_path %>

app/views/authentication/index.html.erb
<h1>Welcome to Strava-Ski!!!</h1>

<p>In order to use Strava-Ski, you must first connect to Strava. To do so, simply click the button below . . . </p>

<%= form_with(url: authentication_doOauth_path, method: :get, local: true) do |form| %>
  <p>
    <%= form.submit("Connect to Strava") %>
  </p> 
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Strava</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stats/index.html.erb
<h1>All Stats</h1>
 
<table>
  <tr>
    <th>Stat Name</th>
    <th>Stat Value</th>
  </tr>
 
  <% @stats.each do |key, value| %>
    <tr>
      <td><%= key %></td>
      <td><%= value %></td>
    </tr>
  <% end %>
</table>

<br/>

<%= link_to 'Home', welcome_index_path %>

app/views/stats/search.html.erb
<h1>Stat: </h1>
 
<table>
  <tr>
    <th>Stat Name</th>
    <th>Stat Value</th>
  </tr>
 
   <tr>
     <td><%= params[:stat_name] %></td>
     <td><%= @stat %></td>
   </tr>
</table>

<br/>

<%= link_to 'Home', welcome_index_path %>

app/views/welcome/index.html.erb
<h1>Strava-Ski</h1>

<br />
<%= image_tag(@athlete_info["profile_medium"]) %>
<br />
<br />
Username: <%= @athlete_info["username"] %>
<br />
Full Name: <%= @athlete_info["firstname"] %> <%= @athlete_info["lastname"] %>
<br />
<br />
<br />

<%= link_to "Show all stats", stats_path %>
<br />
<%= link_to "Show all activities", activities_path %>

<br />
<br />

<%= form_with(url: search_path, local: true) do |form| %>
  <p>
    <%= form.label("Stat Name: ") %>
    <%= form.text_field(:stat_name) %>
    <%= form.submit("Retrieve Stat") %>
  </p> 
<% end %>